name: Tests
on: [push]
jobs:
    tests:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "16.x"
                  registry-url: "https://registry.npmjs.org"
            - name: Tests
              run: |
                  npm ci
                  npm run static
                  npm run test -- --collect-coverage

                  echo "Check we are starting with clean git checkout"
                  if [ -n "$(git status -uno -s)" ]; then echo "git status is not clean"; false; fi
                  echo "Checking that it was built by building"
                  rm -rf docs/eval
                  npm run exec
                  echo "Check that build was unnecessary"
                  if [ -n "$(git status -uno -s)" ]; then echo -e "!!! Changed files."; false; fi
